/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Health"];
          };
        };
      };
    };
  };
  "/portfolio": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Portfolio"];
          };
        };
      };
    };
  };
  "/market/prices": {
    get: {
      parameters: {
        query: {
          ticker: string;
          interval: string;
          from?: string;
          to?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MarketPrices"];
          };
        };
      };
    };
  };
  "/market/macro": {
    get: {
      parameters: {
        query: {
          series: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MacroData"];
          };
        };
      };
    };
  };
  "/weather/events": {
    get: {
      parameters: {
        query?: {
          active?: boolean;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["WeatherEvents"];
          };
        };
      };
    };
  };
  "/sentiment/feed": {
    get: {
      parameters: {
        query?: {
          ticker?: string;
          limit?: number;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SentimentFeed"];
          };
        };
      };
    };
  };
  "/sentiment/aggregate": {
    get: {
      parameters: {
        query: {
          ticker: string;
          window: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SentimentAggregate"];
          };
        };
      };
    };
  };
  "/risk/summary": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["RiskSummary"];
          };
        };
      };
    };
  };
  "/risk/simulate": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            shocks?: {
                target?: string;
                type?: string;
                magnitudePct?: number;
              }[];
            horizonDays?: number;
            paths?: number;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["SimulationResult"];
          };
        };
      };
    };
  };
  "/queries": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            text?: string;
            /** @enum {string} */
            explainLevel?: "expert" | "simple";
            context?: {
              alertId?: string;
            };
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              queryId?: string;
            };
          };
        };
      };
    };
  };
  "/queries/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Query"];
          };
        };
      };
    };
  };
  "/queries/{id}/audit": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["QueryAudit"];
          };
        };
      };
    };
  };
  "/analogs": {
    get: {
      parameters: {
        query?: {
          queryId?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Analogs"];
          };
        };
      };
    };
  };
  "/recommendations/{id}/decision": {
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            decision?: "approve" | "reject";
            note?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/paper-trades": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["Recommendation"][];
          };
        };
      };
    };
  };
  "/alerts": {
    get: {
      parameters: {
        query?: {
          status?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["AlertsResponse"];
          };
        };
      };
    };
  };
  "/alerts/{id}": {
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            status?: "new" | "acknowledged" | "dismissed";
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/monitor/status": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["MonitorStatus"];
          };
        };
      };
    };
  };
  "/backtest/summary": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["BacktestSummary"];
          };
        };
      };
    };
  };
  "/metrics/latency": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["LatencyMetrics"];
          };
        };
      };
    };
  };
  "/audit/log": {
    get: {
      parameters: {
        query?: {
          from?: string;
          to?: string;
          q?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": Record<string, never>[];
          };
        };
      };
    };
  };
  "/system/chaos": {
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            mode?: "none" | "weather_down" | "rate_limited" | "stale_data";
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Health: {
      /** @enum {string} */
      mode?: "live" | "replay" | "degraded";
      degradedReasons?: string[];
      services?: ({
          name?: string;
          status?: string;
          latencyMs?: number;
          /** Format: date-time */
          lastOkAt?: string;
          rateLimit?: {
            remaining?: number;
            /** Format: date-time */
            resetAt?: string;
          } | null;
        })[];
    };
    Portfolio: {
      /** Format: date-time */
      asOf?: string;
      baseCurrency?: string;
      totalValue?: number;
      holdings?: {
          ticker?: string;
          name?: string;
          assetClass?: string;
          exchange?: string;
          sector?: string;
          quantity?: number;
          avgCost?: number;
          lastPrice?: number;
          marketValue?: number;
          weightPct?: number;
          dayChangePct?: number;
          exposureTags?: string[];
        }[];
    };
    MarketPrices: {
      ticker?: string;
      interval?: string;
      source?: string;
      /** Format: date-time */
      asOf?: string;
      candles?: {
          /** Format: date-time */
          t?: string;
          o?: number;
          h?: number;
          l?: number;
          c?: number;
          v?: number;
        }[];
    };
    MacroData: {
      series?: {
          id?: string;
          name?: string;
          unit?: string;
          source?: string;
          /** Format: date-time */
          asOf?: string;
          points?: {
              /** Format: date-time */
              t?: string;
              v?: number;
            }[];
        }[];
    };
    WeatherEvents: {
      events?: {
          id?: string;
          type?: string;
          name?: string;
          severity?: string;
          region?: string;
          /** Format: date-time */
          startsAt?: string;
          /** Format: date-time */
          endsAt?: string;
          /** Format: date-time */
          forecastAsOf?: string;
          source?: string;
          summary?: string;
          affectedTickers?: string[];
        }[];
    };
    SentimentFeed: {
      items?: ({
          id?: string;
          headline?: string;
          source?: string;
          url?: string;
          /** Format: date-time */
          publishedAt?: string;
          tickers?: string[];
          finbert?: {
            label?: string;
            score?: number;
          };
          llm?: {
            label?: string;
            score?: number;
            materiality?: number;
            horizon?: string;
          } | null;
          combinedScore?: number;
          confidence?: number;
          relevance?: {
              ticker?: string;
              score?: number;
            }[];
        })[];
    };
    SentimentAggregate: {
      ticker?: string;
      window?: string;
      points?: {
          /** Format: date-time */
          t?: string;
          score?: number;
          count?: number;
        }[];
    };
    RiskSummary: {
      /** Format: date-time */
      asOf?: string;
      horizonDays?: number;
      var95?: number;
      var99?: number;
      cvar?: number;
      volatility?: number;
      beta?: number;
      exposureBreakdown?: {
          key?: string;
          label?: string;
          weightPct?: number;
          riskContributionPct?: number;
        }[];
      correlation?: {
        tickers?: string[];
        matrix?: number[][];
      };
    };
    SimulationResult: {
      percentiles?: {
          t?: number;
          p5?: number;
          p25?: number;
          p50?: number;
          p75?: number;
          p95?: number;
        }[];
      expectedPnl?: number;
      worstCase?: number;
      /** Format: date-time */
      asOf?: string;
    };
    Query: {
      id?: string;
      text?: string;
      status?: string;
      parsedIntent?: {
        type?: string;
        tickers?: string[];
        horizon?: string;
        eventRef?: string | null;
      };
      plan?: {
          id?: string;
          agent?: string;
          task?: string;
        }[];
      answer?: {
        summary?: string;
        sections?: {
            title?: string;
            body?: string;
          }[];
        range?: {
          median?: number;
          p10?: number;
          p90?: number;
          unit?: string;
          horizonDays?: number;
        } | null;
        confidence?: number;
        counterArgument?: string;
        warnings?: string[];
        degraded?: boolean;
        recommendations?: components["schemas"]["Recommendation"][];
        ledger?: components["schemas"]["LedgerEntry"][];
      };
      latency?: {
          stage?: string;
          ms?: number;
        }[];
    };
    QueryAudit: {
      steps?: {
          stepId?: string;
          agent?: string;
          status?: string;
          /** Format: date-time */
          startedAt?: string;
          /** Format: date-time */
          endedAt?: string;
          input?: string;
          output?: string;
          toolCalls?: {
              name?: string;
              args?: Record<string, never>;
              resultSummary?: string;
            }[];
          evidence?: {
              type?: string;
              ref?: string;
              detail?: string;
            }[];
        }[];
    };
    Analogs: {
      analogs?: {
          id?: string;
          name?: string;
          /** Format: date-time */
          date?: string;
          similarity?: number;
          whySimilar?: {
              factor?: string;
              detail?: string;
            }[];
          outcomes?: {
            d1?: number;
            d5?: number;
            d20?: {
              median?: number;
              p10?: number;
              p90?: number;
            };
          };
        }[];
    };
    AlertsResponse: {
      alerts?: ({
          id?: string;
          /** @enum {integer} */
          tier?: 1 | 2 | 3;
          /** Format: date-time */
          createdAt?: string;
          title?: string;
          reason?: string;
          tickers?: string[];
          anomalyType?: string;
          materiality?: string;
          confidence?: number;
          evidenceIds?: string[];
          linkedQueryId?: string | null;
          /** @enum {string} */
          status?: "new" | "acknowledged" | "dismissed";
          channels?: ({
              /** @enum {string} */
              type?: "pet" | "email" | "telegram";
              status?: string;
            })[];
        })[];
    };
    MonitorStatus: {
      running?: boolean;
      /** Format: date-time */
      lastTickAt?: string;
      watchedTickers?: string[];
      rules?: {
          id?: string;
          name?: string;
          threshold?: number;
          enabled?: boolean;
        }[];
      feeds?: {
          name?: string;
          status?: string;
          /** Format: date-time */
          lastItemAt?: string;
        }[];
    };
    BacktestSummary: {
      /** Format: date-time */
      generatedAt?: string;
      runs?: {
          eventId?: string;
          name?: string;
          /** Format: date-time */
          date?: string;
          prediction?: number;
          actual?: number;
          hit?: boolean;
          errorPct?: number;
        }[];
      metrics?: ({
          /** @enum {string} */
          system?: "multi-source" | "price-only" | "sentiment-only";
          hitRate?: number;
          directionalAccuracy?: number;
          mae?: number;
        })[];
    };
    LatencyMetrics: {
      latest?: {
        ingestionMs?: number;
        embeddingMs?: number;
        indexingMs?: number;
        retrievalMs?: number;
        agentMs?: number;
        totalMs?: number;
      };
      p50?: number;
      p95?: number;
      series?: {
          /** Format: date-time */
          t?: string;
          totalMs?: number;
        }[];
    };
    Recommendation: {
      id?: string;
      /** @enum {string} */
      action?: "hedge" | "reduce" | "increase" | "hold";
      instrument?: string;
      ticker?: string;
      sizePctOfPortfolio?: number;
      rationale?: string;
      expectedImpact?: {
        median?: number;
        p10?: number;
        p90?: number;
        unit?: string;
        horizonDays?: number;
      };
      riskBefore?: number;
      riskAfter?: number;
      confidence?: number;
      /** @enum {string} */
      status?: "proposed" | "approved" | "rejected" | "executed_paper";
      evidenceIds?: string[];
    };
    LedgerEntry: {
      id?: string;
      label?: string;
      value?: number;
      unit?: string;
      /** @enum {string} */
      kind?: "api" | "computed" | "retrieved";
      source?: string;
      toolCall?: {
        name?: string;
        args?: Record<string, never>;
      };
      /** Format: date-time */
      retrievedAt?: string;
      inputs?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
