"""red_team (P9): the 3 strongest reasons the recommendation could be wrong. Code fallback if the LLM fails."""
from __future__ import annotations

import re

from copilot_common.models import RedTeamReport

from ..budget import budget
from ..events import bus
from ..prompt_loader import render
from ..staleness import effective_confidence
from .common import chat, compact, finish_kwargs

_BARE_ID = re.compile(r"(?<!\[)\b(ev_[a-z_]+_\d{3})\b(?!\])")
_BRACKETED = re.compile(r"\s*\[(ev_[a-z_]+_\d{3})\]")
_ANY_BRACKET = re.compile(r"\[[^\]]*\]")


def clean_reasons(reasons: list[str], known_ids: set[str]) -> list[str]:
    """Normalise model citations: 'in ev_analogs_001' → '[ev_analogs_001]'; ids that are not in the evidence are
    removed (the model invented 'ev_missing_001' in evals). A reason that is nothing but an id is dropped."""
    out = []
    for r in reasons:
        r = _BARE_ID.sub(r"[\1]", r.strip())
        r = _BRACKETED.sub(lambda m: f" [{m.group(1)}]" if m.group(1) in known_ids else "", r).strip()
        if _ANY_BRACKET.sub("", r).strip(" .,;:"):
            out.append(r)
    return out


def hedge_check_reasons(ev: list[dict]) -> list[str]:
    """Rules on the out-of-sample hedge back-check (hedge review, phase 2). Always applied, LLM or not."""
    hv = next((e for e in ev if e.get("tool") == "hedge_validation"), None)      # degraded too: n is still n
    if not hv:
        return []
    v, out = hv.get("value") or {}, []
    n, good = v.get("n") or 0, v.get("n_improved") or 0
    if n and good * 2 <= n:
        out.append(f"The hedge did not reduce drawdown in most past analogs ({good} of {n}) [{hv['id']}]")
    elif 0 < n < 5:
        out.append(f"The hedge was only back-checked on {n} past events, too few to trust [{hv['id']}]")
    return out


def code_red_team(state: dict) -> RedTeamReport:
    ev = state.get("evidence", [])
    reasons = hedge_check_reasons(ev)
    for e in ev:
        if e.get("degraded"):
            reasons.append(f"{e['tool']} evidence is degraded ({e.get('degraded_reason')}) [{e['id']}]")
    for e in sorted(ev, key=lambda x: effective_confidence(x) or 1):
        c = effective_confidence(e)
        if c is not None and c < 0.5:
            reasons.append(f"Low confidence in {e['tool']} [{e['id']}]")
    analogs = next((e for e in ev if e["tool"] == "analogs"), None)
    if analogs:
        n = len(analogs["value"].get("analogs", []))
        reasons.append(f"Analog sample is small ({n} events) [{analogs['id']}]")
    reasons.append("Correlations can break down in stress, so the hedge ratio may not hold")
    reasons = list(dict.fromkeys(reasons))[:3]
    n_bad = sum(1 for e in ev if e.get("degraded"))
    verdict = "do not act" if n_bad >= 3 else "proceed with caution"
    return RedTeamReport(reasons=reasons, verdict=verdict,
                         verdict_reason="Generated by rules because the red-team model was unavailable.")


async def red_team(state: dict) -> dict:
    run_id = state["run_id"]
    await bus.emit(run_id, "red_team", "started", host="L3", message="arguing against the recommendation")
    report, status = None, "finished"
    try:
        async with budget("red_team") as b:
            prompt = render("P9", draft=state.get("draft", ""),
                            evidence_json=[compact(e, with_value=False) for e in state.get("evidence", [])])
            res = await chat(state, "red_team", b, "red_team", [{"role": "user", "content": prompt}],
                             schema=RedTeamReport)
            if res.ok and res.parsed is not None:
                report = res.parsed
                report.reasons = clean_reasons(report.reasons, {e["id"] for e in state.get("evidence", [])})[:3]
                must = [r for r in hedge_check_reasons(state.get("evidence", [])) if r not in report.reasons]
                report.reasons = (must + report.reasons)[:3]       # a failed hedge back-check is never dropped
                if not report.reasons:
                    report = None
    except TimeoutError:
        pass
    if report is None:
        report, status = code_red_team(state), "degraded"
    await bus.emit(run_id, "red_team", status, host="L3",
                   **finish_kwargs(b, message=f"verdict: {report.verdict}", verdict=report.verdict))
    return {"red_team": report.model_dump(mode="json"), "latency": {"red_team": b.ms}}
